//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CHTHEntities : DbContext
    {
        public CHTHEntities()
            : base("name=CHTHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAccount> tblAccounts { get; set; }
        public virtual DbSet<tblAccessory> tblAccessories { get; set; }
    
        public virtual ObjectResult<usp_GetAllAccessories_Result> usp_GetAllAccessories(string conditional, Nullable<int> page, Nullable<int> pagesize, ObjectParameter totalRow)
        {
            var conditionalParameter = conditional != null ?
                new ObjectParameter("Conditional", conditional) :
                new ObjectParameter("Conditional", typeof(string));
    
            var pageParameter = page.HasValue ?
                new ObjectParameter("Page", page) :
                new ObjectParameter("Page", typeof(int));
    
            var pagesizeParameter = pagesize.HasValue ?
                new ObjectParameter("Pagesize", pagesize) :
                new ObjectParameter("Pagesize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetAllAccessories_Result>("usp_GetAllAccessories", conditionalParameter, pageParameter, pagesizeParameter, totalRow);
        }
    }
}
